# Generated by Django 5.0.3 on 2024-03-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('product', 'product'), ('service', 'service')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category_owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CategoryMaster',
                'unique_together': {('category_name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=15, unique=True)),
                ('item_name', models.CharField(max_length=250)),
                ('item_file', models.FileField(upload_to='item_files/')),
                ('specification', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_category', to='inventory.categorymaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ItemMaster',
                'unique_together': {('item_name', 'specification')},
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_updator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LocationMaster',
                'unique_together': {('location_name',)},
            },
        ),
        migrations.CreateModel(
            name='InventoryStockMaster',
            fields=[
                ('inventory_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_code', models.CharField(max_length=150)),
                ('inventory_type', models.CharField(choices=[('grn_add', 'grn_add'), ('add_invent', 'add_invent'), ('return', 'return'), ('from_loc', 'from_loc'), ('to_loc', 'to_loc')], max_length=10)),
                ('item_type', models.CharField(choices=[('raw', 'raw_material'), ('finished', 'finished_goods'), ('made-in', 'made-in')], max_length=10)),
                ('batch_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('Kg', 'Kg'), ('Lt', 'Lt'), ('Box', 'Box'), ('One', 'One'), ('Strip', 'Strip')], max_length=10)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_updator', to=settings.AUTH_USER_MODEL)),
                ('item_var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_item_var', to='inventory.itemmaster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_location', to='inventory.locationmaster')),
            ],
            options={
                'db_table': 'InventoryMaster',
            },
        ),
    ]
